### ISSUE TITLE
APP_URL is HTTP, Need Setting for HTTPS

### ISSUE THREAD

**Issue by Ryonez** [getferdi/server#79] opened 2021-11-10 01:35 UTC
I'm having a problem using Ferdi and Ferdi-Server.

At looking at an issues with custom icon not appear, I noticed the url was an http one, which is disallowed (redirected to https at the proxy) on my domains.

Looking at the .env file, I can see the APP_URL is using http, which it shouldn't be, and I can see no configuration option to set this.

Using the docker image: `getferdi/ferdi-server`

**Comment by vraravam** [comment] 2021-11-10 03:35
The `.env` file is not shipped with the base clone/image. Looking at the `.env.example`, you can replicate it and edit it to suit your needs.

**Comment by Ryonez** [comment] 2021-11-10 06:32
@vraravam Please don't close issues before someone has a chance to respond.

The .env is generated from variables passed through docker. APP_URL does not seem to be somethin configurable through this method.

**Comment by xthursdayx** [comment] 2021-11-17 23:00
`APP_URL` is used to specify the local address of your server, something like `http://${HOST}:${PORT}`. For security reasons, the Ferdi-server docker image is not intended to be directly exposed to the internet. Because of this we recommend using a reverse proxy such as NGINX to connect to your Ferdi-server. The variable `EXTERNAL_DOMAIN` is used to tell Ferdi-server what this external domain is, for example `https://ferdi.ryonez.web`.

This is the recommended NGINX block:
```
# Ferdi-server
server {
  listen 443 ssl http2;
  server_name ferdi.my.website;

  # all ssl related config moved to ssl.conf
  include /config/nginx/ssl.conf;

  location / {
    proxy_pass http://<Ferdi-IP>:3333;
    proxy_set_header  X-Real-IP  $remote_addr;
    proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header  Host  $host;
    proxy_set_header  X-Forwarded-Proto  $scheme;
  }
}
```

**Comment by vraravam** [comment] 2021-11-17 23:40
Thanks for the explanation @xthursdayx - I will close my PR without merging.

**Comment by Ryonez** [comment] 2021-11-17 23:41
The APP_URL  was manually set as the server kept using the incorrect url with clients. It is secured behind the proxy, however you can't set the protocol for APP_URL currently (I have the env var ready for when it's implemented.).
Looking at the .env file showed that the APP_URL is formed like this `APP_URL=http://${EXTERNAL_DOMAIN}`. Given this is being giving to clients, which then fail and have problems because http is is not an allowed protocol, I opted to try to override it myself.

For example of client issues, custom service images wouldn't work as it'd attempt to use a url like `http://ferdi.alteria.xyz/v1/icon/559ceb9f-0b16-4a80-a5ee-a0255655dee00fc263ea-9c14-4357-a341-55ab5b0377ed`. This failed, I'm guessing due to the browser detecting mixed content on what's meant to be a https secured page, my reverse proxy routes http urls to https, so that's my best guess.

**Comment by Ryonez** [comment] 2021-11-17 23:44
> Thanks for the explanation @xthursdayx - I will close my PR without merging.

@vraravam Please don't, it's useful in my opinion. Still the APP_URL is my attempt at a workaround. Though it might be work replacing EXTERNAL_DOMAIN with APP_URL and have the administrator configure it accordingly.

**Comment by vraravam** [comment] 2021-11-17 23:48
I have unfortunately closed the PR - but, can resurrect it if needed. Since I dont have enough context on this repo - i will wait for you and @xthursdayx to hash out the best way forward.

**Comment by xthursdayx** [comment] 2021-11-18 17:39
> The APP_URL was manually set as the server kept using the incorrect url with clients. It is secured behind the proxy, however you can't set the protocol for APP_URL currently (I have the env var ready for when it's implemented.).

'APP_URL' is set supposed to be automatically generated by the Ferdi-server docker container based on the default variables `HOST` and `PORT`. These variables are specific to the Ferdi-server docker container and are set in the Dockerfile. They are specifically `0.0.0.0` and `3333`. Thus `APP_URL` will equal `http://0.0.0.0:3333`. `EXTERNAL_DOMAIN` is actually only used by `mail.js`, the mail sender, so it should be inconsequential to any of the issues you're having. I have no idea why `APP_URL` would equal `http://${EXTERNAL_DOMAIN}`, unless `APP_URL` is passed to the container at runtime as `APP_URL=${EXTERNAL_DOMAIN}`. 

I don't really understand why you're having the issues you're having and am unable to reproduce them, so it's difficult for me to help troubleshoot. My best suggestion is that you try to create a new Ferdi-server docker container, making sure to pass all of the variables listed below and see if you still have problems. You'll need to adjust your NGINX proxy conf to point to the correct port you choose for your second Ferdi-server. If you don't have any problems, then the issue is clearly with the configuration of your first Ferdi-server container. If the problem remains then I wonder if the issue is with your local network setup or the server you're running your docker containers on. 

| Parameter | Function |
| :----: | --- |
| `-p <port>:3333` | Will map the container's port 3333 to a port on the host, default is 3333. See the [Docker docs](https://docs.docker.com/config/containers/container-networking/) for more information about port mapping |
| `-e NODE_ENV=development` | for specifying Node environment, production or development, default is development **currently this should not be changed**. See the [Docker docs](https://docs.docker.com/) for more information on the use of environmental variables in [Command-line](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) and [Docker Compose](https://docs.docker.com/compose/environment-variables/) |
| `-e EXTERNAL_DOMAIN=<ferdi-serverdomain>` | for specifying the external domain address of the Ferdi-server |
| `-e DB_CONNECTION=<databasedriver` | for specifying the database being used, default is sqlite, see [below](#supported-databases-and-drivers) for other options |
| `-e DB_HOST=<yourdbhost>` | for specifying the database host, default is 127.0.0.1 |
| `-e DB_PORT=<yourdbport>` | for specifying the database port, default is 3306 |
| `-e DB_USER=<yourdbuser>` | for specifying the database user, default is root |
| `-e DB_PASSWORD=<yourdbpass>` | for specifying the database password, default is password |
| `-e DB_DATABASE=<databasename>` | for specifying the database name to be used, default is ferdi |
| `-e DB_SSL=false` | true only if your database is postgres and it is hosted online, on platforms like GCP, AWS, etc |
| `-e MAIL_CONNECTION=<mailsender>` | for specifying the mail sender to be used, default is smtp |
| `-e SMPT_HOST=<smtpmailserver>` | for specifying the mail host to be used, default is 127.0.0.1 |
| `-e SMTP_PORT=<smtpport>` | for specifying the mail port to be used, default is 2525 |
| `-e MAIL_SSL=true/false` | for specifying SMTP mail security, default is false |
| `-e MAIL_USERNAME=<yourmailusername>` | for specifying your mail username to be used, default is username |
| `-e MAIL_PASSWORD=<yourmailpassword>` | for specifying your mail password to be used, default is password |
| `-e MAIL_SENDER=<sendemailaddress` | for specifying the mail sender address to be used, default is noreply@getferdi.com |
| `-e IS_CREATION_ENABLED=true` | for specifying whether to enable the [creation of custom recipes](#creating-and-using-custom-recipes), default is true |
| `-e IS_DASHBOARD_ENABLED=true` | for specifying whether to enable the Ferdi-server dashboard, default is true |
| `-e IS_REGISTRATION_ENABLED=true` | for specifying whether to allow user registration, default is true |
| `-e CONNECT_WITH_FRANZ=true` | for specifying whether to enable connections to the Franz server, default is true |
| `-e DATA_DIR=data` | for specifying the SQLite database folder, default is data |
| `-v <path to data on host>:/data` | this will store Ferdi-server's data (its database, among other things) on the docker host for persistence. See the [Docker docs](https://docs.docker.com/storage/volumes/) for more information on the use of container volumes |
| `-v <path to recipes on host>:/app/recipes` | this will store Ferdi-server's recipes on the docker host for persistence |

**Comment by Ryonez** [comment] 2021-11-19 00:10
The APP_URL is being used elsewhere, and being passed onto clients. I can reliably reproduce this on my end:

If I use what you suggest:
![image](https://user-images.githubusercontent.com/16157130/142514942-6dcb796e-8fef-4803-88ed-6d5e0bb7e2a6.png)

If I do not set `APP_URL` myself (remove it from the env vars):
![image](https://user-images.githubusercontent.com/16157130/142516258-c662b784-b704-41a4-89f4-74915b0dc4a2.png)


`APP_URL=${EXTERNAL_DOMAIN}` came from a config file, then shifted to an .env file. Both files are renamed to allow the template to manage them currently.

I've removed the container and recreated it. Also removed the template url from the template on unraid as it keeps mucking up things. An update today broke it (data dir default is invalid). That not counting constantly re-adding and exposing the port when I remove it.

Anyway, `APP_URL` is being used by the clients.

**Comment by xthursdayx** [comment] 2021-11-23 15:50
I'm a little confused. Your post says that if you use the variables I suggested, then image source url would equal `http://0.0.0.0:3333`, but that if you "do not set APP_URL [your]self (remove it from the env vars)" the img src would equal `null/v1...`, however the variables I provided said nothing about setting `APP_URL`. I explicitly said not to set it. 

Anyway, I see the problem you're having now and was able to reproduce it by creating a custom service with a custom icon. Using the correct Ferdi-server docker parameters the custom icon img src will equal `null/v1/icon/.....`. This appears to be a problem with the way Ferdi-server is handling custom icons, not a problem with the Docker container parameters. It is related to this commit https://github.com/getferdi/server/commit/26bff86fee36e2bedeee19c750634860e59ed3ec and this previous issue: https://github.com/getferdi/server/issues/9.

I'll work on fixing this and report back.

**Comment by Ryonez** [comment] 2021-11-23 19:07
> I explicitly said not to set it.

That is correct, which is why I attempted not setting it, and setting it to the value you said it should be automatically making, and reported back the issues with doing so. Right now, not setting it myself causes problems, which is why I ended up setting it in the first place. Both of the things you said, that it should be `http://0.0.0.0:3333` internally, and not to set `APP_URL`, do not work.

The custom icon just happens to be the only place I know of that I can see the `APP_URL` being used on the clients.

Looking at what `APP_URL` in this repo, it looks trying to remove it will just cause issues:
![image](https://user-images.githubusercontent.com/16157130/143086984-143adc32-4157-4e76-9eab-f9872e6e17cd.png)

I need the server to give the correct urls to clients. At the moment the only other var is `EXTERNAL_DOMAIN`, but that doesn't even have the protocol. And using `http://0.0.0.0:3333` is going to break things, as demonstrated above.

I don't think there's an issue with that linked commit, it needs to know the URL to use.

Currently I recommend dropping the `EXTERNAL_DOMAIN` and using `APP_URL`, and having the administrators use that. Forget jigsawing different vars together and just have one.

**Comment by xthursdayx** [comment] 2021-11-23 19:41
If you want to submit code to replace `EXTERNAL_DOMAIN` with `APP_URL` as a PR you're welcome to. However, as I noted above, I'm working on fixing the code so that serving custom icons works and so that the Adonis mailer will work as expected. I will report back when I push the fix.

**Comment by xthursdayx** [comment] 2021-11-23 22:49
I believe that this is no fixed by PR https://github.com/getferdi/server/pull/85 so I will close this issue now. However, if you run into any more problems, feel free to reopen it.

**Closed by xthursdayx** 2021-11-23 22:49 UTC
