### ISSUE TITLE
Unable to import my franz account

### ISSUE THREAD

**Issue by Be8ung** [getferdi/server#38] opened 2020-09-17 07:41 UTC
Hi!
(1) I startet with opening the link "https://api.getferdi.com/import" in my browser which produced "Could not login into Franz with your supplied credentials. Please check and try again". I do have a working franz account and can login into my meetfranz account without any problems (https://meetfranz.com/login)!
(2) Then I created a new getferdi account through the app itself with the "same" cretentials as my existing franz account.
(3) when opening "https://api.getferdi.com/import" in the browser again I get  "There was an error while trying to import your account: - There is already a user with this email"

Any chance to import my settings from meetfranz and how?
Best regards!

**Comment by dima2306** [comment] 2020-09-26 10:34
Have the same problem. I can log in into my Franz account but Ferdi server says incorrect credentials.

**Comment by bittner** [comment] 2020-10-21 18:55
This issue is likely related to https://github.com/getferdi/ferdi/issues/1036.

**Comment by bittner** [comment] 2020-10-21 20:27
Duplicate of https://github.com/getferdi/ferdi/issues/927.

**Closed** 2020-10-21 20:28 UTC
